# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dynamic-gateway-service.fullname" . }}
  labels:
    app: {{ template "dynamic-gateway-service.name" . }}
    chart: {{ template "dynamic-gateway-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
spec:
  ports:
    - port: {{ .Values.datapower.gatewayPeeringLocalPort }}
      targetPort: {{ .Values.datapower.gatewayPeeringLocalPort }}
      protocol: TCP
      name: peer-local-port
    - port: {{ .Values.datapower.gatewayPeeringMonitorPort }}
      targetPort: {{ .Values.datapower.gatewayPeeringMonitorPort }}
      protocol: TCP
      name: peer-monit-port
{{- if eq (.Values.datapower.env.enableTMS | default "off") "on" }}
    - port: {{ .Values.datapower.tmsPeeringLocalPort }}
      targetPort: {{ .Values.datapower.tmsPeeringLocalPort }}
      protocol: TCP
      name: tms-local-port
    - port: {{ .Values.datapower.tmsPeeringMonitorPort }}
      targetPort: {{ .Values.datapower.tmsPeeringMonitorPort }}
      protocol: TCP
      name: tms-monit-port
{{- end }}
{{- if eq (.Values.datapower.apiDebugProbe | default "disabled") "enabled" }}
    - port: {{ .Values.datapower.apiDebugProbePeeringLocalPort }}
      targetPort: {{ .Values.datapower.apiDebugProbePeeringLocalPort }}
      protocol: TCP
      name: adp-local-port
    - port: {{ .Values.datapower.apiDebugProbePeeringMonitorPort }}
      targetPort: {{ .Values.datapower.apiDebugProbePeeringMonitorPort }}
      protocol: TCP
      name: adp-monit-port
{{- end }}
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ template "dynamic-gateway-service.name" . }}
    release: {{ .Release.Name }}
---
# Client service for connecting to any GatewayDirector instance
# 
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dynamic-gateway-service.fullname" . }}-ingress
  labels:
    app: {{ template "dynamic-gateway-service.name" . }}
spec:
  ports:
    - port: {{ .Values.datapower.apicGatewayServiceLocalPort }}
      targetPort: {{ .Values.datapower.apicGatewayServiceLocalPort }}
      protocol: TCP
      name: apic-gw-mgmt
    - port: {{ .Values.datapower.apiGatewayLocalPort }}
      targetPort: {{ .Values.datapower.apiGatewayLocalPort }}
      protocol: TCP
      name: api-gw-svc
  #publishNotReadyAddresses: true
  selector:
    app: {{ template "dynamic-gateway-service.name" . }}
    release: {{ .Release.Name }}
